[package]
name = "discrakt"
version = "2.2.3"
edition = "2021"
authors = ["afonsojramos"]
description = "Easy to Use Trakt/Plex Discord Rich Presence"
repository = "https://github.com/afonsojramos/discrakt"
license = "MIT"
keywords = ["discord", "trakt", "rust"]
readme = "README.md"
exclude = [".github/*", "images/*.psd", "credentials.ini", ".gitignore"]

[dependencies]
discord-rich-presence = "0.2.3"
ureq = { version = "2.9.6", features = ["json"] }
configparser = { version = "3.0.2", features = ["indexmap"] }
serde = { version = "1.0.197", features = ["derive"] }
chrono = "0.4.34"
webbrowser = "0.8.13"

[profile.release]
strip = "debuginfo"

[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"
